baseURL = "http://example.org/"
languageCode = "en-us"
title = "charlex.dev"
theme = "hyde"

disqusShortname = "ch4rl3x"
summaryLength = 10

paginate = 5

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

  [[menu.main]]
    name = "Impressum"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/getting-started/"
    weight = -100

[social]
  # e.g.
  github = "https://github.com/ch4rl3x"

[params]
  # Site Author
  author = "Author"
  # Author biography
  bio = "Software Engineer"
  name = "Alexander Karkossa"
  # Site Description, used in HTML meat
  descriptionShort = "Senior developer mobile"
  description = "Employeed as senior developer mobile at Dataport AöR and also working as freelancer android developer"
  enableRSS = true
  # To enable comments, you may need to set `disqusShortname`
  enableComments = true
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics = true

  # Optional
  home= "" # Default: Home
  about= "" # Default: About
  archive= "" # Default: Archive
  tags= "" # Default: Tags
  subscribe= "" # Default: Subscribe
  olderPosts= "" # Default: Older Posts
  newerPosts= "" # Default: Newer Posts
  copyright= "" # Default: © Copyright 2021 ❤️ author
  title404="" # Default: 404 - Page Not Found
  subtitle404= "" # Default: The content you're looking for doesn't seem to exist.
  readMore= "" # Default: Read More